### ISSUE TITLE
Install Issue 

### ISSUE THREAD

**Issue by ahadel** [BadrIT/redmine_scrummer#3]
السلام عليكم
Eng Mahmoud
I have successfully run the install Command BUT the lat one 

-rake redmine_scrummer:load_default_data RAILS_ENV="production" 
- and after selecting Language  [en]

i see this error
# Select language: ar, bg, bs, ca, cs, da, de, el, en, en-GB, es, et, eu, fa, fi, fr, gl, he, hr, hu, id, it, ja, ko, lt, lv, mk, mn, nl, no, pl, pt, pt-BR, ro, ru, sk, sl, sq, sr, sr-YU, sv, th, tr, uk, vi, zh, zh-TW [en] en

Error: undefined method `task?' for #Tracker:0x00000006225b40
Default configuration data was not loaded.

Thanks 
SALAM.

**Comment by mahkhaled** [comment]
Fixed
This was happening because you try to install the plugin over redmine with EXISTING data.
Try to pull my updates and retry

**Comment by ahadel** [comment]
al SLAM alikom
Eng,Mahmoud

i am Still having errors

# Select language: ar, bg, bs, ca, cs, da, de, el, en, en-GB, es, et, eu, fa, fi, fr, gl, he, hr, hu, id, it, ja, ko, lt, lv, mk, mn, nl, no, pl, pt, pt-BR, ro, ru, sk, sl, sq, sr, sr-YU, sv, th, tr, uk, vi, zh, zh-TW [en] en

Error: undefined method `id' for nil:NilClass

SALAM,
Ahmed.

**Comment by mahkhaled** [comment]
Ahmed,

Are you sure you updated your plugin? (check htt, s://github.com/mahkhaled/redmine_scrummer#update-scrummer-plugin)

If yes, please try to send me more info about the error line. Try the following.....
RAILS_ENV=production rake redmine_scrummer:load_default_data --trace

BTW, I think your problem happens because you have some old redmine data

**Comment by ahadel** [comment]
I am sorry to tell you the same problem exist with trace option

root@HOST:/usr/share/redmine# RAILS_ENV=production rake redmine_scrummer:load_default_data --trace
*\* Invoke redmine_scrummer:load_default_data (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
*\* Execute redmine_scrummer:load_default_data

# Select language: ar, bg, bs, ca, cs, da, de, el, en, en-GB, es, et, eu, fa, fi, fr, gl, he, hr, hu, id, it, ja, ko, lt, lv, mk, mn, nl, no, pl, pt, pt-BR, ro, ru, sk, sl, sq, sr, sr-YU, sv, th, tr, uk, vi, zh, zh-TW [en] 

Error: undefined method `id' for nil:NilClass
Default configuration data was not loaded.

Thanks 
ahmed

**Comment by mahkhaled** [comment]
It seems your problem is because you have an existing old data.
Redmine scrummer is recommended for clean redmine

You can open plugins/redmine_scrummer/lib/redmine_scrummer/default_data/loader.rb
leave line by line and retry the rake task till you find the line causing the issue and tell me which line :)

Or simply send me your database backup to mahmoud.khaled@badrit.com if you don't have some private date and I can check it for you myself.
